include("${SUPDEF_PROJECT_CMAKE_DIR}/get_header_list.cmake")

set(
    THREADKILLER_SOURCES_LIST

    "${CMAKE_CURRENT_LIST_DIR}/threadkiller.hpp"
)

get_header_list(
    OUTPUT_VAR THREADKILLER_HEADERS_LIST
    SOURCES_LIST ${THREADKILLER_SOURCES_LIST}
    VERIFY_EXISTS
)