include("${SUPDEF_PROJECT_CMAKE_DIR}/get_header_list.cmake")

set(
    SIGMANAGER_SOURCES_LIST

    "${CMAKE_CURRENT_LIST_DIR}/sigmanager.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/sigmanager.cpp"

    PARENT_SCOPE
)

get_header_list(
    OUTPUT_VAR TMP_SIGMANAGER_HEADERS_LIST
    SOURCES_LIST ${SIGMANAGER_SOURCES_LIST}
    VERIFY_EXISTS
)

set(SIGMANAGER_HEADERS_LIST ${TMP_SIGMANAGER_HEADERS_LIST} PARENT_SCOPE)